
modLoader="javafml"

loaderVersion="${forge_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.20.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40,50)"
ordering = "NONE"
side = "BOTH"